name: downloader
channels:
  - conda-forge
dependencies:
  - affine=2.4.0
  - aom=3.9.1
  - attrs=24.2.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.3
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - dav1d=1.2.1
  - flask=1.1.4
  - freexl=2.0.0
  - geos=3.13.0
  - geotiff=1.7.3
  - giflib=5.2.2
  - icu=75.1
  - itsdangerous=1.1.0
  - jinja2=2.11.3
  - json-c=0.18
  - krb5=1.21.3
  - lerc=4.0.0
  - libarchive=3.7.7
  - libavif16=1.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.10.1
  - libcxx=19.1.5
  - libde265=1.0.15
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgdal-core=3.10.0
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libheif=1.18.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libpng=1.6.44
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.4
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=1.1.1
  - minizip=4.0.7
  - ncurses=6.5
  - numpy=2.1.3
  - openssl=3.4.0
  - pandas=2.2.3
  - pcre2=10.44
  - pip=24.3.1
  - proj=9.5.1
  - pyparsing=3.2.0
  - pyproj=3.7.0
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.1
  - rasterio=1.4.3
  - rav1e=0.6.6
  - readline=8.2
  - setuptools=75.6.0
  - six=1.16.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sqlite=3.47.0
  - svt-av1=2.3.0
  - tk=8.6.13
  - tzdata=2024b
  - uriparser=0.9.8
  - werkzeug=1.0.1
  - wheel=0.45.1
  - x265=3.5
  - xerces-c=3.2.5
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
    - cachetools==5.5.0
    - charset-normalizer==3.4.0
    - deprecated==1.2.15
    - flatbuffers==24.3.25
    - google-api-core==2.23.0
    - google-auth==2.36.0
    - google-cloud-core==2.4.1
    - google-cloud-pubsub==2.27.1
    - google-cloud-storage==2.18.2
    - google-crc32c==1.6.0
    - google-resumable-media==2.7.2
    - googleapis-common-protos==1.66.0
    - grpc-google-iam-v1==0.13.1
    - grpcio==1.68.1
    - grpcio-status==1.68.1
    - idna==3.10
    - importlib-metadata==8.5.0
    - landsatxplore==0.15.0
    - openmeteo-requests==1.3.0
    - openmeteo-sdk==1.18.0
    - opentelemetry-api==1.28.2
    - opentelemetry-sdk==1.28.2
    - opentelemetry-semantic-conventions==0.49b2
    - proto-plus==1.25.0
    - protobuf==5.29.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - requests==2.32.3
    - rsa==4.9
    - shapely==1.8.5.post1
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - urllib3==2.2.3
    - wrapt==1.17.0
    - zipp==3.21.0
